export const konamarketItem = [
  // ...keep your existing 100 items

  // ===== 101 - 200 =====

  { id: 101, name: "Golden Penny Macaroni", imageLink: "/product/spaghetti.jpg" },
  { id: 102, name: "Dangote Spaghetti", imageLink: "/product/spaghetti.jpg" },
  { id: 103, name: "Crown Spaghetti", imageLink: "/product/spaghetti.jpg" },
  { id: 104, name: "Golden Penny Couscous", imageLink: "/product/spaghetti.jpg" },
  { id: 105, name: "Golden Penny Linguine", imageLink: "/product/spaghetti.jpg" },
  { id: 106, name: "Golden Penny Twist Pasta", imageLink: "/product/spaghetti.jpg" },
  { id: 107, name: "Golden Penny Elbow Pasta", imageLink: "/product/spaghetti.jpg" },
  { id: 108, name: "Instant Noodles Pepper Chicken", imageLink: "/product/indomie.jpg" },
  { id: 109, name: "Indomie Onion Chicken", imageLink: "/product/indomie.jpg" },
  { id: 110, name: "Indomie Oriental Fried Noodles", imageLink: "/product/indomie.jpg" },

  { id: 111, name: "Indomie Chicken Pepper Soup", imageLink: "/product/indomie.jpg" },
  { id: 112, name: "Honeywell Chicken Noodles", imageLink: "/product/indomie.jpg" },
  { id: 113, name: "Mimee Chicken Noodles", imageLink: "/product/indomie.jpg" },
  { id: 114, name: "Chikki Beef Noodles", imageLink: "/product/indomie.jpg" },
  { id: 115, name: "Power Pasta", imageLink: "/product/spaghetti.jpg" },
  { id: 116, name: "Rice Flour", imageLink: "/product/garri.jpg" },
  { id: 117, name: "Local White Rice", imageLink: "/product/garri.jpg" },
  { id: 118, name: "Ofada Rice", imageLink: "/product/garri.jpg" },
  { id: 119, name: "Abakaliki Rice", imageLink: "/product/garri.jpg" },
  { id: 120, name: "Jasmine Rice", imageLink: "/product/garri.jpg" },

  { id: 121, name: "Black Eye Beans", imageLink: "/product/garri.jpg" },
  { id: 122, name: "Honey Beans", imageLink: "/product/garri.jpg" },
  { id: 123, name: "Drum Beans", imageLink: "/product/garri.jpg" },
  { id: 124, name: "White Garri Premium", imageLink: "/product/garri.jpg" },
  { id: 125, name: "Yellow Garri", imageLink: "/product/garri.jpg" },
  { id: 126, name: "Ijebu Garri", imageLink: "/product/garri.jpg" },
  { id: 127, name: "Poundo Flour", imageLink: "/product/garri.jpg" },
  { id: 128, name: "Yam Flour", imageLink: "/product/garri.jpg" },
  { id: 129, name: "Plantain Flour", imageLink: "/product/garri.jpg" },
  { id: 130, name: "Cassava Starch", imageLink: "/product/garri.jpg" },

  { id: 131, name: "Peak Filled Milk", imageLink: "/product/peak.jpg" },
  { id: 132, name: "Peak Instant Milk", imageLink: "/product/peak.jpg" },
  { id: 133, name: "Dano Cool Cow Powder", imageLink: "/product/peak.jpg" },
  { id: 134, name: "Cowbell Powder Milk", imageLink: "/product/peak.jpg" },
  { id: 135, name: "Loya Evaporated Milk", imageLink: "/product/peak.jpg" },
  { id: 136, name: "Three Crowns Powder Milk", imageLink: "/product/peak.jpg" },
  { id: 137, name: "Olympic Filled Milk", imageLink: "/product/peak.jpg" },
  { id: 138, name: "Miksi Filled Milk", imageLink: "/product/peak.jpg" },
  { id: 139, name: "Nunu Filled Milk", imageLink: "/product/peak.jpg" },
  { id: 140, name: "Dairy Cream", imageLink: "/product/peak.jpg" },

  { id: 141, name: "Milo Refill", imageLink: "/product/milo.jpg" },
  { id: 142, name: "Bournvita Refill", imageLink: "/product/milo.jpg" },
  { id: 143, name: "Ovaltine Refill", imageLink: "/product/milo.jpg" },
  { id: 144, name: "Nescafe Gold", imageLink: "/product/milo.jpg" },
  { id: 145, name: "Nescafe 3 in 1", imageLink: "/product/milo.jpg" },
  { id: 146, name: "Lipton Yellow Label", imageLink: "/product/milo.jpg" },
  { id: 147, name: "Top Tea Classic", imageLink: "/product/milo.jpg" },
  { id: 148, name: "Twinings Earl Grey", imageLink: "/product/milo.jpg" },
  { id: 149, name: "Chocolate Beverage", imageLink: "/product/milo.jpg" },
  { id: 150, name: "Coffee Mix", imageLink: "/product/milo.jpg" },

  { id: 151, name: "Mamador Classic Oil", imageLink: "/product/oil.jpg" },
  { id: 152, name: "Power Oil Classic", imageLink: "/product/oil.jpg" },
  { id: 153, name: "Devon King's Pure Oil", imageLink: "/product/oil.jpg" },
  { id: 154, name: "Turkey Groundnut Oil", imageLink: "/product/oil.jpg" },
  { id: 155, name: "Sunflower Cooking Oil", imageLink: "/product/oil.jpg" },
  { id: 156, name: "Pure Palm Oil", imageLink: "/product/oil.jpg" },
  { id: 157, name: "Virgin Coconut Oil", imageLink: "/product/oil.jpg" },
  { id: 158, name: "Olive Pomace Oil", imageLink: "/product/oil.jpg" },
  { id: 159, name: "Canola Cooking Oil", imageLink: "/product/oil.jpg" },
  { id: 160, name: "Vegetable Cooking Oil", imageLink: "/product/oil.jpg" },

  { id: 161, name: "Maggi Naija Pot", imageLink: "/product/maggi.jpg" },
  { id: 162, name: "Maggi Signature", imageLink: "/product/maggi.jpg" },
  { id: 163, name: "Knorr Seasoning Powder", imageLink: "/product/maggi.jpg" },
  { id: 164, name: "Ground Curry", imageLink: "/product/maggi.jpg" },
  { id: 165, name: "Ground Thyme", imageLink: "/product/maggi.jpg" },
  { id: 166, name: "Mixed Herbs", imageLink: "/product/maggi.jpg" },
  { id: 167, name: "Garlic Powder", imageLink: "/product/maggi.jpg" },
  { id: 168, name: "Ginger Powder", imageLink: "/product/maggi.jpg" },
  { id: 169, name: "Paprika", imageLink: "/product/maggi.jpg" },
  { id: 170, name: "Cayenne Pepper", imageLink: "/product/maggi.jpg" },

  { id: 171, name: "Refined Sugar", imageLink: "/product/sugar.jpg" },
  { id: 172, name: "Dangote Brown Sugar", imageLink: "/product/sugar.jpg" },
  { id: 173, name: "Golden Penny Flour Premium", imageLink: "/product/sugar.jpg" },
  { id: 174, name: "Honeywell Bakers Flour", imageLink: "/product/sugar.jpg" },
  { id: 175, name: "Whole Wheat Flour", imageLink: "/product/sugar.jpg" },
  { id: 176, name: "Cake Flour", imageLink: "/product/sugar.jpg" },
  { id: 177, name: "Pastry Flour", imageLink: "/product/sugar.jpg" },
  { id: 178, name: "Bread Flour", imageLink: "/product/sugar.jpg" },
  { id: 179, name: "Corn Starch", imageLink: "/product/sugar.jpg" },
  { id: 180, name: "Vanilla Custard", imageLink: "/product/sugar.jpg" },

  { id: 181, name: "Titus Fish", imageLink: "/product/oil.jpg" },
  { id: 182, name: "Geisha Sardines", imageLink: "/product/oil.jpg" },
  { id: 183, name: "Mega Sardines", imageLink: "/product/oil.jpg" },
  { id: 184, name: "Heinz Tomato Ketchup", imageLink: "/product/milo.jpg" },
  { id: 185, name: "Bama Mayonnaise", imageLink: "/product/milo.jpg" },
  { id: 186, name: "Bama Salad Cream", imageLink: "/product/milo.jpg" },
  { id: 187, name: "Sweet Corn Can", imageLink: "/product/peak.jpg" },
  { id: 188, name: "Green Peas Can", imageLink: "/product/peak.jpg" },
  { id: 189, name: "Corned Beef Can", imageLink: "/product/oil.jpg" },
  { id: 190, name: "Tomato Paste Sachet", imageLink: "/product/milo.jpg" },

  { id: 191, name: "Fanta Orange", imageLink: "/product/milo.jpg" },
  { id: 192, name: "Fanta Pineapple", imageLink: "/product/milo.jpg" },
  { id: 193, name: "Schweppes Bitter Lemon", imageLink: "/product/milo.jpg" },
  { id: 194, name: "Schweppes Chapman", imageLink: "/product/milo.jpg" },
  { id: 195, name: "Pepsi", imageLink: "/product/milo.jpg" },
  { id: 196, name: "Mirinda Orange", imageLink: "/product/milo.jpg" },
  { id: 197, name: "Mountain Dew", imageLink: "/product/milo.jpg" },
  { id: 198, name: "Bigi Apple", imageLink: "/product/milo.jpg" },
  { id: 199, name: "Bigi Lemon", imageLink: "/product/milo.jpg" },
  { id: 200, name: "Maltina", imageLink: "/product/milo.jpg" },
];
